spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mathcsbibdb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
  resources:
    chain:
      enabled: true

