spring:
  datasource:
    url: --
    username: --
    password: --
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
  resources:
    chain:
      enabled: true
      
sendgrid:
  credentials:
    hostname: smtp.sendgrid.net
    username: -- 
    password: --

