spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mathcsbibdb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
  resources:
    chain:
      enabled: true

security:
  oauth2:
    client:
      clientId: 1755337141418077
      clientSecret: 006ea0cbd34638fc6fa28f954a3111cd
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me

